### ISSUE TITLE
Using CTkSwitch with Flipper Zero raises KeyError

### ISSUE THREAD

**Issue by Viren070** [rigvedmaanas/CustomTkinterThemes#1]
This is caused by [line 74 in FlipperZero.json](https://github.com/rigvedmaanas/CustomTkinterThemes/blob/711bfd615a53675a0a9d2ded4c44d6a239f5107f/FlipperZero/FlipperZero.json#L51)

It is currently: 

```
    "fg_Color": ["#663b14", "#663b14"],
```

but should be:
```
    "fg_color": ["#663b14", "#663b14"],
```

The incorrectly capitalised r in color causes a KeyError to be raised when attempting to access fg_color for CTkSwitch,

**Comment by rigvedmaanas** [comment]
Hi,

Sorry for the typo error. I have made the suitable changes now.
